# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1024)),
                ('created_at', models.DateField(default=datetime.datetime.today)),
                ('name', models.CharField(max_length=1024)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.today, max_length=1024)),
                ('default_ttl', models.IntegerField(default=None)),
                ('google_profile_id', models.CharField(max_length=1024)),
                ('google_profile_username', models.CharField(max_length=1024)),
                ('google_profile_displayname', models.CharField(max_length=1024)),
                ('facebook_profile_id', models.CharField(max_length=1024)),
                ('facebook_profile_username', models.CharField(max_length=1024)),
                ('facebook_profile_displayname', models.CharField(max_length=1024)),
                ('twitter_profile_id', models.CharField(max_length=1024)),
                ('twitter_profile_username', models.CharField(max_length=1024)),
                ('twitter_profile_displayname', models.CharField(max_length=1024)),
                ('referral', models.CharField(max_length=1024)),
                ('ref_src', models.CharField(max_length=1024)),
                ('first_seen', models.DateField()),
                ('enable_classroom', models.BooleanField(default=False)),
                ('member_of', models.CharField(max_length=1024)),
                ('is_affiliate', models.BooleanField()),
                ('is_aww_admin', models.BooleanField()),
                ('account_type', models.CharField(default='fun', max_length=1024)),
                ('enable_newsletter', models.BooleanField()),
                ('last_login_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=1024)),
                ('last_payment', models.DateField(default=datetime.datetime.today)),
                ('created_at', models.DateField(default=datetime.datetime.today)),
                ('paypal_agreement_id', models.CharField(max_length=1024)),
                ('is_suspended', models.BooleanField(default=False)),
                ('hosts', models.CharField(max_length=1024)),
                ('member_limit', models.IntegerField(default=1)),
                ('period', models.CharField(default='monthly', max_length=1024)),
                ('coupon_iD', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.Subscription'),
        ),
    ]
