# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etl.Account'),
        ),
    ]
